trunk/Facepolls/Polls/urls.py
from django.conf.urls.defaults import patterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('Photopolls.Polls.views',
    (r'^$', 'homepage'),
    (r'cadastroenquete', 'cadastrarenquete'),
    (r'top-polls', 'TopPolls'),
    (r'minha-enquete', 'Minhaenquete'),
    (r'resultados', 'todosresultados'),
    (r'^(?P<enquete_id>\d+)/$', 'detalhe'),
    (r'^(?P<enquete_id>\d+)/resultado/$', 'resultado'),
    (r'^(?P<enquete_id>\d+)/voto/$', 'voto'),
)

trunk/Facepolls/urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
import settings

handler500 = 'Polls.views.page_not_found'
handler404 = 'Polls.views.page_not_found'
admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    (r'^enquete/', include('Photopolls.Polls.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^facebook/', include('django_facebook.urls')),
    #(r'^accounts/', include('django_facebook.auth_urls')),
    #url(r'^admin/', include(admin.site.urls)),
)

trunk/Facepolls/Polls/models.py
# -*-coding:utf-8-*-
from datetime import datetime
from django.db import models

class Enquete(models.Model):
    pergunta = models.CharField(max_length=100)
    data = models.DateTimeField(default=datetime.now())
    votado = models.IntegerField(default=0,blank=True,null=True)
    def __unicode__(self):
        return self.pergunta

    class Meta:
        verbose_name = 'Enquete'
        verbose_name_plural = 'Enquetes'

class Votacao(models.Model):
    perguntaEnquete = models.ForeignKey(Enquete,null=True)
    foto = models.ImageField(upload_to= 'media')
    opcao = models.CharField(max_length=100,blank=True,null=True)
    quantidadevotos = models.IntegerField(default=0,blank=True,null=True)
    def __unicode__(self):
        return self.opcao

    class Meta:
        verbose_name = 'Votação'
        verbose_name_plural = 'Votações'

trunk/Facepolls/Polls/forms.py
from Polls.models import Enquete, Votacao

__author__ = 'Wouker'
from django import forms

class EnqueteForm(forms.ModelForm):
    class Meta:
        model=Enquete
        exclude = ('data','votado')

class VotacaoForm(forms.ModelForm):
    class Meta:
        model = Votacao
        foto = forms.ImageField
        exclude = ('perguntaEnquete','quantidadevotos')

trunk/Facepolls/Polls/views.py
# -*-coding:utf-8-*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext
from Polls.models import Enquete,Votacao

def homepage(request):
    ultimas_5_noticias = Enquete.objects.all().order_by('-data')[:5]
    top_polls = Enquete.objects.all().order_by('-votado')[:3]
    return render_to_response('Polls/index.html',locals(),context_instance=RequestContext(request))

def TopPolls(request):
    ultimas_5_noticias = Enquete.objects.all().order_by('-votado')[:5]
    return render_to_response('Polls/top.html',locals(),context_instance=RequestContext(request))
    #return render_to_response('Polls/index.html', {'ultimas_5_noticias': ultimas_5_noticias})
def Minhaenquete(request):
    ultimas_5_noticias = Enquete.objects.all().order_by('-data')[:5]
    return render_to_response('Polls/top.html',locals(),context_instance=RequestContext(request))
def todosresultados(request):
    ultimas_5_noticias = Enquete.objects.all().order_by('-data')[:5]
    return render_to_response('Polls/resultados.html',locals(),context_instance=RequestContext(request))
#Mostra as opções para voto
def detalhe(request, enquete_id):
    enquete = get_object_or_404(Enquete, pk=enquete_id)
    #return render_to_response('Polls/enquete.html', {'enquete': p})
    return render_to_response('Polls/enquete.html',locals(),context_instance=RequestContext(request))

#def para fazer a votação
def voto(request, enquete_id):
    p = get_object_or_404(Enquete, pk=enquete_id)
    try:
        selected_opcao = p.votacao_set.get(pk=request.POST['opcao'])
    except (KeyError, Votacao.DoesNotExist):
        # Voto errado retorna '0'
        if request.POST:
            return HttpResponse('0')
        return render_to_response('Polls/detalhe.', {
            'enquete': p,
            'error_message': "Você não selecionou nenhuma opção.",
            })
    else:
        selected_opcao.quantidadevotos += 1
        selected_opcao.save()
        p.votado += 1
        p.save()
        # Voto certo retorna '1'
        #if request.POST:
            #return HttpResponse('1')
        return render_to_response('Polls/voto-criado.html', locals(), context_instance=RequestContext(request))
        #return HttpResponseRedirect('/enquete/'+str(p.id)+'/resultado')

def resultado(request, enquete_id):
    enquete = get_object_or_404(Enquete, pk=enquete_id)
    return render_to_response('Polls/result.html',locals(),context_instance=RequestContext(request))

def cadastrarenquete(request):
    from forms import VotacaoForm,EnqueteForm

    if request.method == 'POST':
        #form1 = VotacaoForm(request.POST, request.FILES)
        #form = EnqueteForm(request.POST, request.FILES)
        novaEnquete = Enquete(pergunta = request.POST['pergunta'])
        novaEnquete.save()
        iteracao = 0
        for opcao in request.POST:
            if iteracao >0:
                novaVotacao = Votacao(perguntaEnquete = novaEnquete, foto = request.FILES['foto'+str(iteracao)],opcao = request.POST['opcao'+str(iteracao)] )
                novaVotacao.save()
            iteracao += 1
        #if form1.is_valid():
            #novo_votacao = form.save(commit=False)
            #novo_votacao.perguntaEnquete_id = novo_enquete.id
            #novo_votacao = form1.save()


        return render_to_response('Polls/enquete-criada.html',locals(), context_instance=RequestContext(request))
    else:
        form = EnqueteForm()#fuu
        form1 = VotacaoForm()
    return render_to_response('Polls/minha-enquete.html', locals(), context_instance=RequestContext(request))

def page_not_found(request):
    return render_to_response('Polls/404.html', locals(), context_instance=RequestContext(request))

trunk/Facepolls/templates/Polls/cadastroenquete.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title></title>
</head>
<body>
<form enctype="multipart/form-data" action="" method="post" id="form1">
    {{ form }}
    <div class="campo-form">
        <div class="campo-nome"><strong><label for="id_opcao">*Opcao</label></strong></div><input id="id_opcao" class="validate[required] input-large" type="text" maxlength="255" name="opcao1" value="">
    </div>
    <div class="campo-form">
        <div class="campo-nome"><strong><label for="id_foto">*Foto</label></strong></div><input id="id_foto" class="validate[required] input-large" type="file" maxlength="255" name="foto1" value="">
    </div>
    <div class="campo-form">
        <div class="campo-nome"><strong><label for="id_opcao">*Opcao1</label></strong></div><input id="id_opcao" class="validate[required] input-large" type="text" maxlength="255" name="opcao2" value="">
    </div>
    <div class="campo-form">
        <div class="campo-nome"><strong><label for="id_foto">*Foto1</label></strong></div><input id="id_foto" class="validate[required] input-large" type="file" maxlength="255" name="foto2" value="">
    </div>

    <input type="submit" />
</form>
</body>
</html>

trunk/Facepolls/templates/Polls/detalhe.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<h1>{{ enquete.pergunta }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="/enquete/{{ enquete.id }}/voto/" method="post">
    {% for votacao in enquete.votacao_set.all %}
        <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ votacao.id }}" />
        <label for="opcao{{ forloop.counter }}">{{ votacao.opcao }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>
</body>
</html>

trunk/Facepolls/templates/Polls/enquete-criada.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
    <title></title>
    <link href="{{ MEDIA_URL }}css/layout.css" rel="stylesheet" type="text/css">
	<link href="{{ MEDIA_URL }}css/fileuploader.css" rel="stylesheet" type="text/css">
    <script src="{{ MEDIA_URL }}js/jquery-1.4.2.min.js" type="text/jsscript"></script>
	
</head>
<body>
<div id="container">
    <div id="principal">
        <div id="logo">
            <a href="{% url Polls.views.homepage %}">
                <img src="{{ MEDIA_URL }}img/logo.png">
            </a>
        </div>
        <div id="menu">
            <div id="itensMenu">
                <a href="{% url Polls.views.todosresultados %}">resultados</a>
                <a href="{% url Polls.views.Minhaenquete %}">minha enquete</a>
                <a href="#">publicas</a>
                <a href="{% url Polls.views.TopPolls %}">top polls</a>
                <a href="#">ajuda</a>
            </div>
            <div id="btnCriarEnquete">
                <a href="{% url Polls.views.cadastrarenquete %}">
                    <img src="{{ MEDIA_URL }}img/btn_criar_s1.jpg">
                </a>
            </div>
        </div>
        <div id="box3">
            <div id="box3Interna">
                <div id="topHeader3">
                </div>
                <div id="containerTopPolls">
               		 	     <div style="float: left;width: 100%; height: 200px;line-height: 250px;font-family: arial;font-size: 33px;color: #FFCC00;">Enquete criada com sucesso!</div>
               </div>
            </div>
            <div id="shadow3"></div>
        </div>
        <div id="footer">
            <div id="internaFooter">Todos os diretos reservados a Wesley Coutinho e Nataliel Vasconcelos</div>

        </div>

    </div>
</div>
</body>
</html>

trunk/Facepolls/templates/Polls/enquete.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
    <title></title>
    <link href="{{ MEDIA_URL }}css/layout.css" rel="stylesheet" type="text/css">
	<script type="text/javascript" async src="{{ MEDIA_URL }}js/ga.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.3.2.js"></script>
    <script src="{{ MEDIA_URL }}js/jquery.capSlide.js" type="text/javascript"></script>
    <script type="text/javascript">
            $(function() {
                $("#capslide_img_cont").capslide({
                    caption_color	: 'white',
                    caption_bgcolor	: 'black',
                    overlay_bgcolor : 'black',
                    border			: '',
                    showcaption	    : false
                });
            });
        </script>
	<script type="text/javascript">
            $(function() {
                $("#capslide_img_cont2").capslide({
                    caption_color	: 'white',
                    caption_bgcolor	: 'black',
                    overlay_bgcolor : 'black',
                    border			: '',
                    showcaption	    : false
                });
            });
        </script>


</head>
<body>
<div id="container">
    <div id="principal">
        <div id="logo">
            <a href="{% url Polls.views.homepage %}">
                <img src="{{ MEDIA_URL }}img/logo.png">
            </a>
        </div>
        <div id="menu">
            <div id="itensMenu">
                <a href="{% url Polls.views.todosresultados %}">resultados</a>
                <a href="{% url Polls.views.Minhaenquete %}">minha enquete</a>
                <a href="#">publicas</a>
                <a href="{% url Polls.views.TopPolls %}">top polls</a>
                <a href="#">ajuda</a>
            </div>
            <div id="btnCriarEnquete">
                <a href="{% url Polls.views.cadastrarenquete %}">
                    <img src="{{ MEDIA_URL }}img/btn_criar_s1.jpg">
                </a>
            </div>
        </div>
        <div id="box3">
            <div id="box3Interna">
                <div id="topHeader3">
                </div>
                <div id="containerTopPolls">
                    <p class="ask">{{ enquete.pergunta }}</p>
                </div>
                <form action="/enquete/{{ enquete.id }}/voto/" method="post">
                {% for votacao in enquete.votacao_set.all|slice:"0:1" %}
                    <a id="opcao1">
                        <div id="capslide_img_cont" class="ic_container" style="width: 250px; height: 310px; ">
                            <img src="{{ MEDIA_URL }}{{ votacao.foto }}" alt="" width="240px" height="300px">
                            <div class="overlay" style="background-color: black; display: none; "></div>
                            <div class="ic_caption" style="color: white; background-color: black; bottom: 0px; width: 250px; display: none; ">
                                <p class="ic_category">Opção</p>
                                <h3>{{ votacao.opcao }}</h3>
                                <input type="radio" name="opcao" id="{{ forloop.counter }}" value="{{ votacao.id }}" />
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                {% for votacao in enquete.votacao_set.all|slice:"1:2" %}
                <a id="opcao2">
                	<div id="capslide_img_cont2" class="ic_container" style="width: 250px; height: 310px; ">
                        <img src="{{ MEDIA_URL }}{{ votacao.foto }}" alt="" width="240px" height="300px">
                    	<div class="overlay" style="background-color: black; display: none; "></div>
                        <div class="ic_caption" style="color: white; background-color: black; bottom: 0px; width: 250px; display: none; ">
							<p class="ic_category">Opção</p>
                        	<h3>{{ votacao.opcao }}</h3>
                            <input type="radio" name="opcao" id="{{ forloop.counter }}" value="{{ votacao.id }}" />
                        </div>
                    </div>
                </a>
                {% endfor %}




               	<div class="votar-button">

                       <input type="submit" value="Votar" />
                </div>
                </form>
                    <div class="versus3"><img src="{{ MEDIA_URL }}img/versus.png"></div>
            </div>
            <div id="shadow3"></div>
        </div>
        <div id="footer">
            <div id="internaFooter">Todos os diretos reservados a Wesley Coutinho e Nataliel Vasconcelos</div>

        </div>

    </div>
</div>
</body>
</html>

trunk/Facepolls/templates/Polls/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
    <title></title>
    <link href="{{ MEDIA_URL }}css/layout.css" rel="stylesheet" type="text/css">
	<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.4.2.min.js"></script>
<!--
  jCarousel library
-->
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.jcarousel.min.js"></script>
<!--
  jCarousel skin stylesheet
-->
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/skin.css">

<script type="text/javascript">

function mycarousel_initCallback(carousel)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });

    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });

    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

jQuery(document).ready(function() {
    jQuery('#mycarousel').jcarousel({
        auto: 2,
        wrap: 'last',
        initCallback: mycarousel_initCallback
    });
});

</script>

</head>
<body>
<div id="container">
    <div id="principal">
        <div id="logo">
            <a href="{% url Polls.views.homepage %}">
                <img src="{{ MEDIA_URL }}img/logo.png">
            </a>
        </div>
        <div id="menu">
            <div id="itensMenu">
                <a href="{% url Polls.views.todosresultados %}">resultados</a>
                <a href="{% url Polls.views.Minhaenquete %}">minha enquete</a>
                <a href="#">publicas</a>
                <a href="{% url Polls.views.TopPolls %}">top polls</a>
                <a href="#">ajuda</a>
            </div>
            <div id="btnCriarEnquete">
                <a href="{% url Polls.views.cadastrarenquete %}">
                    <img src="{{ MEDIA_URL }}img/btn_criar_s1.jpg">
                </a>
            </div>
        </div>
        <link href="{{ STATIC_URL }}css/facebook.css" type="text/css" rel="stylesheet" media="all" />
        {% include 'django_facebook/_facebook_js.html' %}
        <form action="{% url facebook_connect %}?facebook_login=1" method="post">
            <a href="javascript:void(0);" style="font-size: 20px;" onclick="F.connect(this.parentNode);">Register, login or connect with facebook</a>
            <input type="hidden" value="{{ request.path }}" name="next" />
        </form>
        <div id="box1">
            <div id="box1Interna">
                <div id="topHeader">
                    <img src="{{ MEDIA_URL }}img/ultimas.png">
                </div>
                <div id="jquery">
                    
<div id="wrap">

  <div class=" jcarousel-skin-tango">
  	<div class="jcarousel-container jcarousel-container-horizontal">
        <div class="jcarousel-clip jcarousel-clip-horizontal">

        	<ul id="mycarousel" class="jcarousel-list jcarousel-list-horizontal">
                {% for enquete in ultimas_5_noticias %}
    			<li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal" jcarouselindex="1">
                    <a style="text-decoration: none;" href="{{ enquete.id }}"><h4 class="ask1">{{ enquete.pergunta }}</h4>
                    {% for votacao in enquete.votacao_set.all %}
                	<div class="versus"><img src="{{ MEDIA_URL }}img/versus.png"></div>
                    <div id="box-question"><img src="{{ MEDIA_URL }}{{ votacao.foto }}"width="219" height="154"></div></a>
                    {% endfor %}
                </li>
                {% endfor %}
  			</ul>

         </div>
         <div class="jcarousel-prev jcarousel-prev-horizontal jcarousel-prev-disabled jcarousel-prev-disabled-horizontal" disabled="true"><img src="{{ MEDIA_URL }}img/prev.png">
     </div>
     <div class="jcarousel-next jcarousel-next-horizontal" disabled="false"><img src="{{ MEDIA_URL }}img/next.png">
  	</div>
  </div>
</div>

</div>
                </div>
            </div>
            <div id="shadow1"></div>
        </div>
        <div id="box2">

            <div id="topCuriosos">
                <img src="{{ MEDIA_URL }}img/topCuriosos.png">
            </div>
            <div id="facebookAvatar">

            </div>
        </div>
        <div id="shadow4"></div>
        <div id="box3">
            <div id="box3Interna">
                <div id="topHeader3">
                    <img src="{{ MEDIA_URL }}img/topPolls.png">
                </div>
                <div id="containerTopPolls">
                    {% for top in top_polls %}
                    <div id="primeiro">
                        <div id="imdFirt">
                            <p class="first">{{ forloop.counter }}°</p>
                        </div>
                        <div id="Q1">
                            <a href="{{ top.id }}" class="questao">{{ top.pergunta }}</a>
                        </div>
                        <div id="imgs">
                            {% for votacao in top.votacao_set.all %}
                                <div id="vot1">
                                    <div id="borda">
                                        <img src="{{ MEDIA_URL }}{{ votacao.foto }}" alt="" width="70px" height="87px">
                                    </div>
                                    <div id="votos">
                                        <p>{{ votacao.quantidadevotos }} voto{{ votacao.quantidadevotos|pluralize }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                            	<div id="separa2"></div>
                        </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            <div id="shadow3"></div>
        </div>
        <div id="footer">
            <div id="internaFooter">Todos os diretos reservados a Wesley Coutinho e Nataliel Vasconcelos</div>

        </div>

    </div>
</div>
</body>
</html>

trunk/Facepolls/templates/Polls/minha-enquete.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link href="{{ MEDIA_URL }}css/fileuploader.css" rel="stylesheet" type="text/css">
    <script src="{{ MEDIA_URL }}js/jquery.js" type="text/javascript"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/busca.js"></script>
	
</head>
<body>		
    <div id="container">
    <div id="principal">
        <div id="logo">
            <a href="{% url Polls.views.homepage %}">
                <img src="{{ MEDIA_URL }}img/logo.png">
            </a>
        </div>
        <div id="menu">
            <div id="itensMenu">
                <a href="{% url Polls.views.todosresultados %}">resultados</a>
                <a href="{% url Polls.views.Minhaenquete %}">minha enquete</a>
                <a href="#">publicas</a>
                <a href="{% url Polls.views.TopPolls %}">top polls</a>
                <a href="#">ajuda</a>
            </div>
            <div id="btnCriarEnquete">
                <a href="{% url Polls.views.cadastrarenquete %}">
                    <img src="{{ MEDIA_URL }}img/btn_criar_s1.jpg">
                </a>
            </div>
        </div>
        <div id="box3">
            <div id="box3Interna">
                <div id="topHeader3">
                </div>
                <div id="containerTopPolls">
                    <form enctype="multipart/form-data" action="" method="post" id="form1" name="busca">
                    <div class="pergunta">


							<ul class="campo-busca">
    							<li><input class="input-busca" type="text"  name="pergunta" value="Escreva aqui sua pergunta" /></li>
							</ul>


                        </div>

                        <div id="opcao1">
							<input type="text" class="borda2" name="opcao1"/>
                            <input type="file" name="foto1">
                        </div>
            			<div id="opcao2">
                            <input type="text" class="borda2" name="opcao2"/>
                            <input type="file" name="foto2">
                        </div>

                              <div class="versus2"><img src="{{ MEDIA_URL }}img/versus.png"></div>

							<div class="button"><button class="finalizar"></button><input type="submit" /></div>
                    </form>
               </div>
            </div>
            <div id="shadow3"></div>
        </div>
        <div id="footer">
            <div id="internaFooter">Todos os diretos reservados a Wesley Coutinho e Nataliel Vasconcelos</div>

        </div>

    </div>
</div>
</body>
</html>

trunk/Facepolls/templates/Polls/result.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
    <title></title>
    <link href="{{ MEDIA_URL }}css/layout.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" async src="{{ MEDIA_URL }}js/ga.js"></script>

</head>
<body>
<div id="container">
    <div id="principal">
        <div id="logo">
            <a href="{% url Polls.views.homepage %}">
                <img src="{{ MEDIA_URL }}img/logo.png">
            </a>
        </div>
        <div id="menu">
            <div id="itensMenu">
                <a href="{% url Polls.views.todosresultados %}">resultados</a>
                <a href="{% url Polls.views.Minhaenquete %}">minha enquete</a>
                <a href="#">publicas</a>
                <a href="{% url Polls.views.TopPolls %}">top polls</a>
                <a href="#">ajuda</a>
            </div>
            <div id="btnCriarEnquete">
                <a href="{% url Polls.views.cadastrarenquete %}">
                    <img src="{{ MEDIA_URL }}img/btn_criar_s1.jpg">
                </a>
            </div>
        </div>
        </div>
        <div id="box3">
            <div id="box3Interna">
                <div id="topHeader3">
                </div>
                <div id="containerTopPolls">
                    <p class="ask">Resultado</p>
                    <p class="ask">{{ enquete.pergunta }}</p>
                {% for votacao in enquete.votacao_set.all|slice:"0:1" %}
                    <a id="opcao1">
                        <div id="capslide_img_cont" class="ic_container" style="width: 250px; height: 310px; ">
                            <img src="{{ MEDIA_URL }}{{ votacao.foto }}" alt="" width="240px" height="300px">
                            <div class="overlay" style="background-color: black; display: none; "></div>
                            <div class="ic_caption" style="color: white; background-color: black; bottom: 0px; width: 250px; display: none; ">
                                <p class="ic_category">Opção</p>
                                <h3>{{ votacao.opcao }}</h3>
                                <input type="radio" name="opcao" id="{{ forloop.counter }}" value="{{ votacao.id }}" />
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                {% for votacao in enquete.votacao_set.all|slice:"1:2" %}
                <a id="opcao2">
                	<div id="capslide_img_cont2" class="ic_container" style="width: 250px; height: 310px; ">
                        <img src="{{ MEDIA_URL }}{{ votacao.foto }}" alt="" width="240px" height="300px">
                    	<div class="overlay" style="background-color: black; display: none; "></div>
                        <div class="ic_caption" style="color: white; background-color: black; bottom: 0px; width: 250px; display: none; ">
							<p class="ic_category">Opção</p>
                        	<h3>{{ votacao.opcao }}</h3>
                            <input type="radio" name="opcao" id="{{ forloop.counter }}" value="{{ votacao.id }}" />
                        </div>
                    </div>
                </a>
                    <li>{{ votacao.opcao }} -- {{ votacao.quantidadevotos }} voto{{ votacao.quantidadevotos|pluralize }}</li>
                {% endfor %}

                    <div class="versus3"><img src="{{ MEDIA_URL }}img/versus.png"></div>
            </div>
            <div id="shadow3"></div>
        </div>
        <div id="footer">
            <div id="internaFooter">Todos os diretos reservados a Wesley Coutinho e Nataliel Vasconcelos</div>

        </div>

    </div>
</div>
</body>
</html>

trunk/Facepolls/templates/Polls/resultado.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<h1>{{ enquete.pergunta }}</h1>

<ul>
    {% for votacao in enquete.votacao_set.all %}
        <li>{{ votacao.opcao }} -- {{ votacao.quantidadevotos }} voto{{ votacao.quantidadevotos|pluralize }}</li>
    {% endfor %}
</ul>
</body>
</html>